---
- name: "Create a node user {{ gobetween_healthcheck_user }} on {{ delegate_host }}"
  ansible.builtin.user:
    name: "{{ gobetween_healthcheck_user }}"
    state: present
    shell: /bin/bash
    expires: -1
  failed_when: false
  delegate_to: "{{ delegate_host }}"

- name: "Create sudoersd file for the user"
  ansible.builtin.template:
    src: "gobetween.sudo.j2"
    dest: "/etc/sudoers.d/gobetween.sudo"
    owner: root
    group: root
    mode: '0644'

- name: "Set node user password valid time on {{ delegate_host }}"
  ansible.builtin.command: chage -M 99999 {{ gobetween_healthcheck_user }}
  changed_when: false
  delegate_to: "{{ delegate_host }}"

- name: "Deploy {{ gobetween_healthcheck_user }} authorized_key on {{ delegate_host }}"
  ansible.posix.authorized_key:
    user: "{{ gobetween_healthcheck_user }}"
    key: "{{ gobetween_ssh_user.ssh_public_key }}"
    state: present
  delegate_to: "{{ delegate_host }}"
