---
- name: "Create {{ gobetween_owner_group }} system group"
  ansible.builtin.group:
    name: "{{ gobetween_owner_group }}"
    system: true
    state: present

- name: "Create {{ gobetween_owner }} system user"
  ansible.builtin.user:
    name: "{{ gobetween_owner }}"
    system: true
    shell: "/usr/sbin/nologin"
    group: "{{ gobetween_owner_group }}"
    createhome: false

- name: "Create an install dir {{ gobetween_install_dir }}"
  ansible.builtin.file:
    path: "{{ gobetween_install_dir }}"
    state: directory
    owner: "{{ gobetween_owner_group }}"
    group: "{{ gobetween_owner_group }}"
    mode: '0755'

- name: "Create log file"
  ansible.builtin.file:
    path: "{{ gobetween_log_file }}"
    state: touch
    owner: "{{ gobetween_owner_group }}"
    group: "{{ gobetween_owner_group }}"
    mode: '0644'
  changed_when: false

- name: "Install tasks"
  when: not gobetween_binary.stat.exists or ( gobetween_ins_version is defined and gobetween_ins_version.stdout != "0.8.0+snapshot")
  block:
    - name: "Install requierements"
      ansible.builtin.package:
        name: "ca-certificates"
        state: present
      register: pkg_result
      retries: 12
      delay: 10
      until: pkg_result is success

    - name: "Download gobetween..."
      ansible.builtin.get_url:
        url: "{{ gobetween_tgz_url }}"
        dest: "/tmp/{{ gobetween_tgz }}"
        timeout: 120
        mode: '0644'
      when: not gobetween_install_local

    - name: "Unarchive gobetween..."
      ansible.builtin.unarchive:
        remote_src: true
        src: "/tmp/{{ gobetween_tgz }}"
        dest: "/tmp/"
        mode: '0644'
      when: not gobetween_install_local

    - name: "Copy gobetween binary..."
      ansible.builtin.copy:
        src: "/tmp/gobetween"
        dest: "{{ gobetween_binary_file }}"
        mode: '0755'
        remote_src: true
      when: not gobetween_install_local

    - name: "Copy gobetween local binary..."
      ansible.builtin.copy:
        src: '{{ gobetween_local_file }}'
        dest: '{{ gobetween_binary_file }}'
        mode: '0755'
      when: gobetween_install_local
